Pzsp2 33 odbieranie zgloszen i konkursow z backendu wyswietlanie
kozlowskimaciej/because-its-worth-contest-platform pull request #7
Opened 2023-12-06 11:30 UTC by misat1505

2023-12-06 11:32 UTC, misat1505 commented
just review the requests and responses prototypes

2023-12-06 11:40 UTC, kozlowskimaciej commented
There shouldn’t be no nie warto, because everything is warto

2023-12-08 22:05 UTC, kubao503 requested changes

2023-12-08 22:05 UTC, kubao503 commented on README.md
> +{
There should be contest_id as foreign key

2023-12-17 18:03 UTC, closed without merging